"""empty message

Revision ID: 43b54980ffae
Revises: 
Create Date: 2025-04-11 21:02:39.078353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b54980ffae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_color_id'), 'color', ['id'], unique=False)
    op.create_index(op.f('ix_color_uid'), 'color', ['uid'], unique=True)
    op.create_table('height',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_height_id'), 'height', ['id'], unique=False)
    op.create_index(op.f('ix_height_uid'), 'height', ['uid'], unique=True)
    op.create_table('memory_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_memory_size_id'), 'memory_size', ['id'], unique=False)
    op.create_index(op.f('ix_memory_size_uid'), 'memory_size', ['uid'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_index(op.f('ix_product_uid'), 'product', ['uid'], unique=True)
    op.create_table('product_color',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'color_id')
    )
    op.create_table('product_height',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('height_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['height_id'], ['height.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'height_id')
    )
    op.create_table('product_memory_size',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('memory_size_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['memory_size_id'], ['memory_size.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'memory_size_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_memory_size')
    op.drop_table('product_height')
    op.drop_table('product_color')
    op.drop_index(op.f('ix_product_uid'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_memory_size_uid'), table_name='memory_size')
    op.drop_index(op.f('ix_memory_size_id'), table_name='memory_size')
    op.drop_table('memory_size')
    op.drop_index(op.f('ix_height_uid'), table_name='height')
    op.drop_index(op.f('ix_height_id'), table_name='height')
    op.drop_table('height')
    op.drop_index(op.f('ix_color_uid'), table_name='color')
    op.drop_index(op.f('ix_color_id'), table_name='color')
    op.drop_table('color')
    # ### end Alembic commands ###